#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include
#include <wx/wxprec.h>
#include <wx/dcclient.h>
#include <wx/filedlg.h>
#include <wx/clipbrd.h>
#include <wx/print.h>
#include <wx/printdlg.h>
#include <memory>
#include "ImageHolder.h"
#include <windows.h>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void b_LoadFromFile_Click( wxCommandEvent& event );
		void b_SaveToFile_Click( wxCommandEvent& event );
		void b_Copy_Click( wxCommandEvent& event );
		void b_Print_Click( wxCommandEvent& event );
		void m_PageSettings_Click( wxCommandEvent& event );
		void m_Preview_Click( wxCommandEvent& event );
		void m_Print_Click( wxCommandEvent& event );
		void m_Quit_Click( wxCommandEvent& event );
		void m_About_Click( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
	private:
		ImageHolder* _image;
		std::shared_ptr<wxPageSetupDialogData> _pageSetupData;


};

#endif // __GUIMyFrame1__
